spring.application.name=SpringBootSDPDietBalancer

# PostgreSQL (Render Deployment)
spring.datasource.url=jdbc:postgresql://dpg-d7qnkmosfn5c73bc1ml0-a:5432/nutribalancedb
spring.datasource.username=nutribalancedb_user
spring.datasource.password=r4HhDiLUnADUoe9wyrBblZkuAuYceumW
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Dynamic Port (IMPORTANT for deployment)
server.port=${PORT:8080}
